"""LangGraph agent state definition.

Defines the typed state that flows through the agent graph.
Each node reads from and writes to this shared state.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


class AgentPhase(StrEnum):
    """Current phase of the agent execution."""

    INIT = "init"
    RAG_SEARCH = "rag_search"
    CACHE_CHECK = "cache_check"
    MCP_QUERY = "mcp_query"
    REFLECTION = "reflection"
    RESPONSE = "response"
    CLARIFICATION = "clarification"
    ERROR = "error"


class TableMatch(BaseModel):
    """A table match from RAG search."""

    table_name: str
    warehouse_id: str
    owner: str
    columns: list[str] = Field(default_factory=list)
    description: str = ""
    score: float = 0.0


class QueryPlan(BaseModel):
    """SQL query plan generated by the LLM."""

    warehouse_id: str
    table_name: str
    sql: str
    purpose: str = ""


class QueryResult(BaseModel):
    """Result from executing a query via MCP."""

    warehouse_id: str
    table_name: str
    sql: str
    data: list[dict[str, Any]] = Field(default_factory=list)
    row_count: int = 0
    cached: bool = False
    error: str = ""


class AgentState(TypedDict, total=False):
    """Shared state for the LangGraph agent.

    This state flows through all nodes in the graph. Each node
    reads the fields it needs and writes back its results.
    """

    # User input
    user_query: str
    conversation_history: list[dict[str, str]]

    # Current phase tracking
    phase: str
    iteration: int

    # RAG search results
    rag_matches: list[dict[str, Any]]

    # Query planning
    query_plans: list[dict[str, Any]]
    needs_clarification: bool
    clarification_question: str

    # Cache results
    cache_hits: list[dict[str, Any]]
    cache_misses: list[dict[str, Any]]

    # MCP query results
    query_results: list[dict[str, Any]]

    # LLM reflection / analysis
    analysis: str

    # Final response
    response: str
    error: str

    # Available warehouses for context
    available_warehouses: list[dict[str, str]]
